packages:
    - packages/cli
    - packages/core
    - packages/converter
    - packages/parser
    - packages/rust
    - packages/js-ts
    - packages/python
    - packages/csharp
    - packages/kotlin
    - packages/patches
    - apps/*
    - tests/*
    - scripts/*

ignoredBuiltDependencies:
    - esbuild
    - unrs-resolver
